Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2020-11, with the labels that each got.

#1266 dependabot upgrades
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1266

#1267 upgrade org.springframework.boot
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1267

#1275 upgrade helm version
  Jenkinsfile_CNP
  charts/bulk-scan-orchestrator/Chart.yaml
  charts/bulk-scan-orchestrator/requirements.yaml
  charts/bulk-scan-orchestrator/values.preview.template.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1275

#1277 add bunch of dependabot upgrades
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1277

#1262 Added logs to attaching documents
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/model/ccd/mappers/SupplementaryEvidenceMapper.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/AttachToCaseCallbackService.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/helper/LoggerTestUtil.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/model/ccd/mappers/SupplementaryEvidenceMapperTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1262

#1282 add probate deceased surname mapping
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1282
