Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2021-09, with the labels that each got.

#1546 Code smells
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/ExceptionRecordFinalizerTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/ReclassifyCallbackServiceTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1546

#1547 Code smells
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/ExceptionRecordFinalizerTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1547

#1548 Log case ref
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/envelopehandlers/SupplementaryEvidenceHandler.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1548

#1555 bump 'org.flywaydb.flyway' version '7.15.0'
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1555

#1558 DTSBPS-749 suppress vulnerability
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1558

#1565 DTSBPS-755 - Bump versions.junit from 5.7.2 to 5.8.1
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1565

#1570 upgdare junit5PluginVersion for pitest
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1570

#1569 bump versions-failed dependabot PRs
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1569
