Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2021-06, with the labels that each got.

#1444 Code smells
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/CreateCaseCallbackService.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/callback/ExceptionRecordValidator.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1444

#1446 Tests for case creation
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/CcdNewCaseCreator.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/CcdNewCaseCreatorTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1446

#1447 remove unnecessary suppression
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1447

#1448 avoid CVE-2021-22118
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1448

#1449 DTSBPS-627 remove unnecessary jars dep. management
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1449

#1452 Update DockerImage to new tagging reference
  Jenkinsfile_CNP
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1452

#1453 DTSBPS-650 upgrade java chart
  charts/bulk-scan-orchestrator/Chart.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1453
