Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2021-02, with the labels that each got.

#1327 Cleanup suppressions
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1327

#1340 avoid netty vulnerability
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1340

#1341 DTSBPS-369: Spring boot version bump
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1341

#1345 Bump core-case-data-store-client from 4.7.5 to 4.7.6
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1345

#1344 Bump idam-client from v1.5.5 to 2.0.0
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1344
