Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2021-08, with the labels that each got.

#1493 DTSBPS-687: fortify integration on nightly build
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1493

#1497 Added tests
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/callback/ExceptionRecordValidatorTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1497

#1500 Refactored EventIdValidator
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/AttachToCaseCallbackService.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/CreateCaseCallbackService.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/EventIdValidator.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/callback/ExceptionRecordValidator.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/AttachToCaseCallbackServiceTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/EventIdValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/callback/ExceptionRecordValidatorTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1500

#1502 ExceptionRecordAttacher
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/ExceptionRecordAttacherTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1502

#1503 DTSBPS-708 - Upgrade to GitHub-native Dependabot (#1423)
  .github/dependabot.yml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1503

#1514 Added tests for legacy id
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/ExceptionRecordAttacherTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1514

#1529 dependabot bumps 1522PR and 1505PR
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1529

#1530 Bump postgresql to 42.2.23and netflix
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1530

#1533 DTSBPS-712 arrange dependencies
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1533

#1543 DTSBPS-722 fix terraform error
  infrastructure/state.tf
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1543

#1542 Code smells
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/ExceptionRecordFinalizer.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/ScannedDocumentValidator.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/SupplementaryEvidenceUpdater.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/callback/ExceptionRecordValidator.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/servicebus/domains/envelopes/EnvelopeMessageProcessor.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/client/caseupdate/CaseUpdateRequestCreatorTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/client/transformation/EnvelopeTransformerTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/controllers/CcdCallbackControllerReclassifyTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/feature/OcrDataOrderTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/model/ccd/mappers/ExceptionRecordMapperTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/EnvelopeMessageProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/QueueProcessingReadinessCheckerTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/ccd/CaseFinderTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1542
