Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2022-11, with the labels that each got.

#2116 Add distribution to Github actions (DTSBPS-1147)
  .github/workflows/ci.yml
  .github/workflows/swagger.yml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2116

#2147 DTSBPS-1163: Suppress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2147

#2152 DTSBPS-1167: Suppress CVE-2022-29885
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2152

#2168 Revert "Bump info.solidsoft.pitest from 1.7.0 to 1.9.11"
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2168
