Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2022-06, with the labels that each got.

#1869 DTSBPS-960: Suppress CVE-2022-22976
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1869

#1878 DTSBPS-978: Suppressed CVE-2022-22978
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1878

#1880 Removed suppressions
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1880

#1898 Suppress CVE-2022-34305
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1898
