Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2022-04, with the labels that each got.

#1786 Suppressed vulnerability
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1786

#1793 Suppress vulnerability
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1793

#1797 upgrade spring-boot version
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1797

#1810 Suppressed vulnerability
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1810
