Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2022-05, with the labels that each got.

#1825 Resolve CVE-2022-24823 (DTSBPS-943)
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1825

#1829 Suppress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1829

#1830 Suppress CVE-2022-29885 (DTSBPS-947)
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1830

#1850 DTSBPS-954: Revert pitest version
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1850
