Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2022-08, with the labels that each got.

#1975 Suppress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1975

#1980 Suppress CVE-2022-29885
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1980

#1981 Revert "Bump info.solidsoft.pitest from 1.7.0 to 1.9.0"
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1981

#1983 Add backstage configuration file
  catalog-info.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-1983
