Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2022-10, with the labels that each got.

#2060 Update terraform azuread and azurerm versions (DTSBPS-1100)
  config/owasp/suppressions.xml
  infrastructure/state.tf
Labels: ns:bsp, prd:bulk-scan, no-changes, rel:bulk-scan-orchestrator-pr-2060

#2064 Suppress CVE-2022-42003 and CVE-2022-42004 (DTSBPS-1111)
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2064

#2080 Upgraded junit-jupiter
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2080

#2097 Configure privatelaw case transformation URL (DTSBPS-1133)
  charts/bulk-scan-orchestrator/Chart.yaml
  charts/bulk-scan-orchestrator/values.yaml
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2097
