Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2023-03, with the labels that each got.

#2358 DTSBPS-1325: Fix CVE 2023 24998
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2358

#2370 adding local db
  .env
  .gitignore
  docker-compose.yml
  docker/database/Dockerfile
  docker/database/init-db.sh
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2370

#2379 Fix CVE 2022 40152
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2379

#2395 delete scripts
  bin/create-env-file.sh
  bin/setup-env.sh
  bin/substitutions.json
  docker-compose.yml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2395
