Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2023-01, with the labels that each got.

#2238 DTSBPS-1235: Fix CVE 2021 4277
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2238

#2242 DTSBPS-1236: Fix CVE 2022 31692
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2242

#2261 DTSBPS-1249: Update Dockerfile
  Dockerfile
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2261

#2282 DTSBPS-1258: Upgrade appinsights
  Dockerfile
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2282

#2283 DTSBPS-1276: cleanup suppressions
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2283
