Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2023-02, with the labels that each got.

#2293 DTSBPS-1282: Upgrade checkstyle version and cleanup Dockerfile
  Dockerfile
  build.gradle
  charts/bulk-scan-orchestrator/values.yaml
  config/checkstyle/checkstyle.xml
  lib/AI-Agent.xml
  lib/applicationinsights.json
  src/integrationTest/java/uk/gov/hmcts/reform/bulkscan/orchestrator/data/CallbackResultRepositoryTest.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/services/servicebus/domains/envelopes/EnvelopeMessageProcessor.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2293

#2301 DTSBPS-1293: Suppress vulneratilities
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2301

#2303 DTSBPS-1290: Bump chart
  charts/bulk-scan-orchestrator/Chart.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2303

#2307 DTSBPS-1294: Remove unused variable
  infrastructure/variables.tf
Labels: ns:bsp, prd:bulk-scan, no-changes, rel:bulk-scan-orchestrator-pr-2307

#2342 DTSBPS-1308-orchestrator-mutation-test-fix
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2342

#2350 DTSBPS-1318: Fix CVE 2022 45688
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2350
