Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2024-10, with the labels that each got.

#2696 update pact to latest version
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2696

#2697 FACT-2013 app insights refine logging
  lib/applicationinsights.json
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2697

#2700 Revert "FACT-2013 app insights refine logging"
  lib/applicationinsights.json
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2700
