Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2025-06, with the labels that each got.

#2757 FACT-2424
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/config/JacksonConfigurationVerifier.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/config/ObjectMapperConfiguration.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2757

#2758 FACT-2408 dependency updates
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2758

#2763 FACT-2449 added classifier all
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2763
