Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2025-04, with the labels that each got.

#2736 FACT-2294 dependancy updates
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2736

#2739 bump to java 5.3.0
  charts/bulk-scan-orchestrator/Chart.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2739

#2742 FACT-2181 undo orchestrator ibca changes
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2742

#2744 FACT-1482 payment flyway migration
  src/main/resources/db/migration/V002__new_tables.sql
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2744

#2745 FACT-2361 Remove Pact and cleanup
  .github/dependabot.yml
  Jenkinsfile_CNP
  build.gradle
  src/contractTest/java/uk/gov/hmcts/reform/bulkscan/orchestrator/.gitkeep
  src/contractTest/java/uk/gov/hmcts/reform/bulkscan/orchestrator/client/transformation/SampleAppConsumerTest.java
  src/contractTest/resources/.gitkeep
  src/contractTest/resources/transformation/request/invalid-exception-record.json
  src/contractTest/resources/transformation/request/valid-exception-record.json
  src/contractTest/resources/transformation/response/last-name-required.json
  src/contractTest/resources/transformation/response/success.json
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2745
