Repository hmcts/bulk-scan-orchestrator, pull requests merged in 2025-01, with the labels that each got.

#2724 FACT-2069 changed postgres bits to 15
  charts/bulk-scan-orchestrator/values.aat.template.yaml
  charts/bulk-scan-orchestrator/values.preview.template.yaml
  docker/database/Dockerfile
  src/functionalTest/resources/application.yaml
  src/integrationTest/resources/application.properties
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2724

#2726 FACT-1952 adds SSCS8 form type to surname config
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2726

#2727 changes for sscs8 service config
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-orchestrator-pr-2727
